### PR TITLE
Impl 129

### LINKED ISSUE #129: Implement templating functionalities for tabular pages
As discussed with Huyeng, it would be benefitial to be able to define customized layouts and functionalities for the tabular pages depending on the use case. ODC wants to implement a series of custom filters which are difficult to implement generically.

For implementing this, we need to:
- [ ] Maintain a templates folder on the plugins code structure
- [ ] Implement specific template for ODC's laws
- [ ] Provide the configuration options for selecting a specific template for a determined tabular page

### PR DESCRIPTION
**Pull request by Huyeng**
- Create template layout
- Update the configuration of law
- Update the template to correspond with the configure. 

Fixes #129

### CODE REVIEW

**Comment by acorbi** [comment]
@Huyeng I have deployed this branch on PP, commit 1 code enhancement (please see) and also identified the following warning on https://pp.opendevelopmentmekong.net/wp-admin/post.php?post=4085766&action=edit and https://pp.opendevelopmentcambodia.net/wp-admin/post.php?post=98002&action=edit

screenshot from 2017-02-20 11-52-52

Can you please fix it so I can continue my review? Also, I noticed that you are managing the "localization" of the options differently as we were doing before. You are using now [en] or [localization] for managing them while on other options such as **_attributes_values_mapping** we are storing a separate value **_attributes_values_mapping_localization**. Please unify this implementation otherwise is too confusing...

**Comment by Huyeng** [comment]
I will fix it now. 
I don't think it will confuse. The _attributes_values_mapping is using to match the key/id of CKAN with the label on front-end. 
The _attributes_filters_group_list[en]/[localization], those are just the label to show up on the site. The labels can change to update as the editor needs both Khmer and English. 

screenshot_5

**Comment by acorbi** [comment]
@Huyeng What I mean it can be confusing is that the same functionality is implemented differently. this could be confusing for other developers looking at the code. thanks for fixing the warning, ping me when it is ready and I will continue testing

**Comment by Huyeng** [comment]
Ok. Which one do you prefer, array or variable?

**Pull request merged**
